In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("AI_Job_Layoffs_Dataset.csv")

In [4]:
df.head()

,event_id,date,year,quarter,month,company_name,industry,region,country,company_size,...,role_category,seniority_level,ai_exposure_score,stated_reason,ai_cited_as_reason,revenue_growth_yoy_pct,ai_capex_change_yoy_pct,stock_price_change_30d_pct,shifted_staff_to_ai_roles,source_type
0,LAYOFF-00001,02/01/2023,2023,Q1,January,HelioIndustries,Technology/Software,North America,United States,"Mid-Market (1,000-10,000)",...,Consulting/Advisory,Mid-Level (3-7 yrs),54,Market/Economic Conditions,No,-29.4,-10.4,0.9,No,Earnings Call Transcript
1,LAYOFF-00002,03/01/2023,2023,Q1,January,FalconSystems,Retail/E-commerce,Europe,Netherlands,"Enterprise (10,000+)",...,Software Engineering,Senior (8-15 yrs),60,Overhiring Correction,No,30.3,47.8,-9.5,No,CEO Memo
2,LAYOFF-00003,06/01/2023,2023,Q1,January,DeltaSystems,Media/Content,North America,United States,"SMB (200-1,000)",...,Software Engineering,Senior (8-15 yrs),51,Cost-Cutting,No,-12.6,3.6,-4.4,No,Press Release
3,LAYOFF-00004,07/01/2023,2023,Q1,January,AstraHoldings,Finance/Banking,Europe,Ireland,"SMB (200-1,000)",...,Content/Creative,Mid-Level (3-7 yrs),59,AI/Automation,Yes,21.2,58.6,-2.1,Yes,News Report
4,LAYOFF-00005,09/01/2023,2023,Q1,January,BriIndustries,Technology/Software,Asia Pacific,Singapore,"Mid-Market (1,000-10,000)",...,Sales,Entry-Level (0-2 yrs),77,Overhiring Correction,No,-23.8,29.7,-14.5,No,News Report

In [5]:
df.tail()

,event_id,date,year,quarter,month,company_name,industry,region,country,company_size,...,role_category,seniority_level,ai_exposure_score,stated_reason,ai_cited_as_reason,revenue_growth_yoy_pct,ai_capex_change_yoy_pct,stock_price_change_30d_pct,shifted_staff_to_ai_roles,source_type
1345,LAYOFF-01346,26/06/2026,2026,Q2,June,NovaCorp,Technology/Software,North America,United States,"SMB (200-1,000)",...,Sales,Entry-Level (0-2 yrs),60,Overhiring Correction,No,-1.5,17.5,7.9,No,Earnings Call Transcript
1346,LAYOFF-01347,26/06/2026,2026,Q2,June,QuantGlobal,Finance/Banking,Asia Pacific,China,"Mid-Market (1,000-10,000)",...,Software Engineering,Mid-Level (3-7 yrs),50,Merger/Acquisition,No,4.8,21.3,-15.5,Yes,SEC Filing
1347,LAYOFF-01348,26/06/2026,2026,Q2,June,HarborTechnologies,Consulting/Professional Services,Europe,Ireland,"SMB (200-1,000)",...,Customer Support,Mid-Level (3-7 yrs),71,AI/Automation,Yes,22.2,22.3,-11.1,Yes,News Report
1348,LAYOFF-01349,26/06/2026,2026,Q2,June,NovaGroup,Technology/Software,Asia Pacific,Japan,"SMB (200-1,000)",...,Sales,Mid-Level (3-7 yrs),34,AI/Automation,Yes,5.7,61.8,5.3,No,CEO Memo
1349,LAYOFF-01350,27/06/2026,2026,Q2,June,PacePartners,Pharma/Chemicals,North America,Canada,"Mid-Market (1,000-10,000)",...,Operations,Entry-Level (0-2 yrs),41,Cost-Cutting,No,-7.0,41.0,-7.9,No,SEC Filing

In [6]:
print("Rows and Columns :", df.shape)

Rows and Columns : (1350, 24)

In [7]:
df.columns

Index(['event_id', 'date', 'year', 'quarter', 'month', 'company_name',
       'industry', 'region', 'country', 'company_size',
       'total_workforce_before', 'headcount_cut', 'workforce_after',
       'pct_workforce_cut', 'role_category', 'seniority_level',
       'ai_exposure_score', 'stated_reason', 'ai_cited_as_reason',
       'revenue_growth_yoy_pct', 'ai_capex_change_yoy_pct',
       'stock_price_change_30d_pct', 'shifted_staff_to_ai_roles',
       'source_type'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   event_id                    1350 non-null   object
 1   date                        1350 non-null   object
 2   year                        1350 non-null   int64
 3   quarter                     1350 non-null   object
 4   month                       1350 non-null   object
 5   company_name                1350 non-null   object
 6   industry                    1350 non-null   object
 7   region                      1350 non-null   object
 8   country                     1350 non-null   object
 9   company_size                1350 non-null   object
 10  total_workforce_before      1350 non-null   int64
 11  headcount_cut               1350 non-null   int64
 12  workforce_after             1350 non-null   int64
 13  pct_workforce_cut           1350 non-null   float64
 14  role_category               1350 non-null   object
 15  seniority_level             1350 non-null   object
 16  ai_exposure_score           1350 non-null   int64
 17  stated_reason               1350 non-null   object
 18  ai_cited_as_reason          1350 non-null   object
 19  revenue_growth_yoy_pct      1350 non-null   float64
 20  ai_capex_change_yoy_pct     1350 non-null   float64
 21  stock_price_change_30d_pct  1350 non-null   float64
 22  shifted_staff_to_ai_roles   1350 non-null   object
 23  source_type                 1350 non-null   object
dtypes: float64(4), int64(5), object(15)
memory usage: 253.3+ KB

In [9]:
df.dtypes

event_id                       object
date                           object
year                            int64
quarter                        object
month                          object
company_name                   object
industry                       object
region                         object
country                        object
company_size                   object
total_workforce_before          int64
headcount_cut                   int64
workforce_after                 int64
pct_workforce_cut             float64
role_category                  object
seniority_level                object
ai_exposure_score               int64
stated_reason                  object
ai_cited_as_reason             object
revenue_growth_yoy_pct        float64
ai_capex_change_yoy_pct       float64
stock_price_change_30d_pct    float64
shifted_staff_to_ai_roles      object
source_type                    object
dtype: object

In [10]:
df.describe()

,year,total_workforce_before,headcount_cut,workforce_after,pct_workforce_cut,ai_exposure_score,revenue_growth_yoy_pct,ai_capex_change_yoy_pct,stock_price_change_30d_pct
count,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000
mean,2024.807407,35772.913333,2457.245926,33315.667407,6.980274,53.366667,7.986148,20.458741,-0.445556
std,1.053754,58578.273796,5202.597470,54633.191002,4.837882,21.230904,15.206205,23.232045,8.021726
min,2023.000000,52.000000,5.000000,47.000000,0.500000,2.000000,-46.900000,-20.000000,-23.400000
25%,2024.000000,615.000000,31.000000,548.500000,3.482500,39.000000,-2.400000,3.975000,-6.000000
50%,2025.000000,4276.500000,231.000000,3983.000000,5.755000,51.000000,8.250000,19.150000,-0.500000
75%,2026.000000,52283.000000,1703.000000,49336.500000,9.357500,67.000000,18.800000,36.375000,4.675000
max,2026.000000,218796.000000,52864.000000,214826.000000,34.050000,99.000000,52.400000,93.000000,30.000000

In [11]:
df.describe(include='object')

,event_id,date,quarter,month,company_name,industry,region,country,company_size,role_category,seniority_level,stated_reason,ai_cited_as_reason,shifted_staff_to_ai_roles,source_type
count,1350,1350,1350,1350,1350,1350,1350,1350,1350,1350,1350,1350,1350,1350,1350
unique,1350,743,4,12,315,12,5,19,4,14,4,7,2,2,6
top,LAYOFF-00001,07/04/2026,Q2,June,AstraHoldings,Technology/Software,North America,Mexico,"Enterprise (10,000+)",Legal,Mid-Level (3-7 yrs),AI/Automation,No,No,News Report
freq,1,9,463,170,11,292,782,271,460,123,484,600,750,1105,408

In [12]:
df.isnull().sum()

event_id                      0
date                          0
year                          0
quarter                       0
month                         0
company_name                  0
industry                      0
region                        0
country                       0
company_size                  0
total_workforce_before        0
headcount_cut                 0
workforce_after               0
pct_workforce_cut             0
role_category                 0
seniority_level               0
ai_exposure_score             0
stated_reason                 0
ai_cited_as_reason            0
revenue_growth_yoy_pct        0
ai_capex_change_yoy_pct       0
stock_price_change_30d_pct    0
shifted_staff_to_ai_roles     0
source_type                   0
dtype: int64

In [13]:
(df.isnull().sum()/len(df))*100

event_id                      0.0
date                          0.0
year                          0.0
quarter                       0.0
month                         0.0
company_name                  0.0
industry                      0.0
region                        0.0
country                       0.0
company_size                  0.0
total_workforce_before        0.0
headcount_cut                 0.0
workforce_after               0.0
pct_workforce_cut             0.0
role_category                 0.0
seniority_level               0.0
ai_exposure_score             0.0
stated_reason                 0.0
ai_cited_as_reason            0.0
revenue_growth_yoy_pct        0.0
ai_capex_change_yoy_pct       0.0
stock_price_change_30d_pct    0.0
shifted_staff_to_ai_roles     0.0
source_type                   0.0
dtype: float64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.columns = df.columns.str.strip()

In [18]:
df.columns

Index(['event_id', 'date', 'year', 'quarter', 'month', 'company_name',
       'industry', 'region', 'country', 'company_size',
       'total_workforce_before', 'headcount_cut', 'workforce_after',
       'pct_workforce_cut', 'role_category', 'seniority_level',
       'ai_exposure_score', 'stated_reason', 'ai_cited_as_reason',
       'revenue_growth_yoy_pct', 'ai_capex_change_yoy_pct',
       'stock_price_change_30d_pct', 'shifted_staff_to_ai_roles',
       'source_type'],
      dtype='object')

In [21]:
numerical_columns = df.select_dtypes(include=['int64','float64']).columns

for col in numerical_columns:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\gracy\AppData\Local\Temp\ipykernel_19216\482762825.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [22]:
print(df.columns.tolist())

['event_id', 'date', 'year', 'quarter', 'month', 'company_name', 'industry', 'region', 'country', 'company_size', 'total_workforce_before', 'headcount_cut', 'workforce_after', 'pct_workforce_cut', 'role_category', 'seniority_level', 'ai_exposure_score', 'stated_reason', 'ai_cited_as_reason', 'revenue_growth_yoy_pct', 'ai_capex_change_yoy_pct', 'stock_price_change_30d_pct', 'shifted_staff_to_ai_roles', 'source_type']

In [23]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [24]:
df['date'].head()

0   2023-02-01
1   2023-03-01
2   2023-06-01
3   2023-07-01
4   2023-09-01
Name: date, dtype: datetime64[ns]

In [25]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month_name()
df['quarter'] = df['date'].dt.quarter

In [26]:
df[['date','year','month','quarter']].head()

        date    year      month  quarter
0 2023-02-01  2023.0   February      1.0
1 2023-03-01  2023.0      March      1.0
2 2023-06-01  2023.0       June      2.0
3 2023-07-01  2023.0       July      3.0
4 2023-09-01  2023.0  September      3.0

In [27]:
categorical_columns = [
    'industry',
    'country',
    'company_size',
    'role_category',
    'seniority_level',
    'stated_reason',
    'ai_cited_as_reason',
    'shifted_staff_to_ai_roles'
]

for col in categorical_columns:
    print(f"\n{col}")
    print(df[col].unique())

industry
['Technology/Software' 'Retail/E-commerce' 'Media/Content'
 'Finance/Banking' 'Healthcare' 'Manufacturing' 'Consumer Internet'
 'Consulting/Professional Services' 'Energy' 'Pharma/Chemicals' 'Telecom'
 'Transportation/Logistics']

country
['United States' 'Netherlands' 'Ireland' 'Singapore' 'Australia' 'China'
 'Mexico' 'UAE' 'Canada' 'Argentina' 'Japan' 'France' 'Chile' 'India'
 'Germany' 'United Kingdom' 'Brazil' 'South Africa' 'Saudi Arabia']

company_size
['Mid-Market (1,000-10,000)' 'Enterprise (10,000+)' 'SMB (200-1,000)'
 'Startup (<200)']

role_category
['Consulting/Advisory' 'Software Engineering' 'Content/Creative' 'Sales'
 'Finance/Accounting' 'Marketing' 'Data Entry/Back Office' 'Operations'
 'Legal' 'Product Management' 'IT/Infrastructure'
 'Manufacturing/Production' 'Customer Support' 'HR/People Ops']

seniority_level
['Mid-Level (3-7 yrs)' 'Senior (8-15 yrs)' 'Entry-Level (0-2 yrs)'
 'Executive/Leadership']

stated_reason
['Market/Economic Conditions' 'Overhiring Correction' 'Cost-Cutting'
 'AI/Automation' 'Restructuring/Reorg' 'Merger/Acquisition' 'Other']

ai_cited_as_reason
['No' 'Yes']

shifted_staff_to_ai_roles
['No' 'Yes']

In [28]:
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [29]:
df.isnull().sum()

event_id                        0
date                          728
year                          728
quarter                       728
month                         728
company_name                    0
industry                        0
region                          0
country                         0
company_size                    0
total_workforce_before          0
headcount_cut                   0
workforce_after                 0
pct_workforce_cut               0
role_category                   0
seniority_level                 0
ai_exposure_score               0
stated_reason                   0
ai_cited_as_reason              0
revenue_growth_yoy_pct          0
ai_capex_change_yoy_pct         0
stock_price_change_30d_pct      0
shifted_staff_to_ai_roles       0
source_type                     0
dtype: int64

In [30]:
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

for col in numerical_columns:
    df[col] = df[col].fillna(df[col].median())

In [31]:
categorical_columns = df.select_dtypes(include='object').columns

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   event_id                    1350 non-null   object
 1   date                        622 non-null    datetime64[ns]
 2   year                        1350 non-null   float64
 3   quarter                     1350 non-null   float64
 4   month                       1350 non-null   object
 5   company_name                1350 non-null   object
 6   industry                    1350 non-null   object
 7   region                      1350 non-null   object
 8   country                     1350 non-null   object
 9   company_size                1350 non-null   object
 10  total_workforce_before      1350 non-null   int64
 11  headcount_cut               1350 non-null   int64
 12  workforce_after             1350 non-null   int64
 13  pct_workforce_cut           1350 non-null   float64
 14  role_category               1350 non-null   object
 15  seniority_level             1350 non-null   object
 16  ai_exposure_score           1350 non-null   int64
 17  stated_reason               1350 non-null   object
 18  ai_cited_as_reason          1350 non-null   object
 19  revenue_growth_yoy_pct      1350 non-null   float64
 20  ai_capex_change_yoy_pct     1350 non-null   float64
 21  stock_price_change_30d_pct  1350 non-null   float64
 22  shifted_staff_to_ai_roles   1350 non-null   object
 23  source_type                 1350 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(4), object(13)
memory usage: 253.3+ KB

In [33]:
df.info()

df.isnull().sum()

df.columns.tolist()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   event_id                    1350 non-null   object
 1   date                        622 non-null    datetime64[ns]
 2   year                        1350 non-null   float64
 3   quarter                     1350 non-null   float64
 4   month                       1350 non-null   object
 5   company_name                1350 non-null   object
 6   industry                    1350 non-null   object
 7   region                      1350 non-null   object
 8   country                     1350 non-null   object
 9   company_size                1350 non-null   object
 10  total_workforce_before      1350 non-null   int64
 11  headcount_cut               1350 non-null   int64
 12  workforce_after             1350 non-null   int64
 13  pct_workforce_cut           1350 non-null   float64
 14  role_category               1350 non-null   object
 15  seniority_level             1350 non-null   object
 16  ai_exposure_score           1350 non-null   int64
 17  stated_reason               1350 non-null   object
 18  ai_cited_as_reason          1350 non-null   object
 19  revenue_growth_yoy_pct      1350 non-null   float64
 20  ai_capex_change_yoy_pct     1350 non-null   float64
 21  stock_price_change_30d_pct  1350 non-null   float64
 22  shifted_staff_to_ai_roles   1350 non-null   object
 23  source_type                 1350 non-null   object
dtypes: datetime64[ns](1), float64(6), int64(4), object(13)
memory usage: 253.3+ KB

['event_id',
 'date',
 'year',
 'quarter',
 'month',
 'company_name',
 'industry',
 'region',
 'country',
 'company_size',
 'total_workforce_before',
 'headcount_cut',
 'workforce_after',
 'pct_workforce_cut',
 'role_category',
 'seniority_level',
 'ai_exposure_score',
 'stated_reason',
 'ai_cited_as_reason',
 'revenue_growth_yoy_pct',
 'ai_capex_change_yoy_pct',
 'stock_price_change_30d_pct',
 'shifted_staff_to_ai_roles',
 'source_type']

In [34]:
df.to_csv("AI_Job_Layoffs_Cleaned.csv", index=False)

In [35]:
import os

print(os.getcwd())

C:\Users\gracy

In [36]:
import os

downloads_path = os.path.join(os.path.expanduser("~"), "Downloads")

df.to_csv(os.path.join(downloads_path, "AI_Job_Layoffs_Cleaned.csv"), index=False)

print("File saved successfully!")

File saved successfully!